[build]
  # Build command for client-only build
  command = "npm install && npx --yes vite@5.4.14 build"
  
  # Directory to publish (built files)
  publish = "dist"
  
  # Build environment variables
  environment = { NODE_VERSION = "20" }

[build.processing]
  # Skip processing of JS files (they're already optimized by Vite)
  skip_processing = false

# Redirect all requests to index.html for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variables (these will need to be set in Netlify dashboard)
[context.production.environment]
  NODE_ENV = "production"
  VITE_GEMINI_API_KEY = ""

[context.deploy-preview.environment]
  NODE_ENV = "development"
  VITE_GEMINI_API_KEY = ""

[context.branch-deploy.environment]
  NODE_ENV = "development"
  VITE_GEMINI_API_KEY = ""